### PR TITLE
Add html css files

### PR DESCRIPTION
**Pull request by scientistsagoemarcus**

### CODE REVIEW

**Comment by scientistsagoemarcus** [comment]
add html and css files to the Hello Microverse project.

**Comment by scientistsagoemarcus** [comment]
add-html-css -files to the project with a .gitignore folder.

**Review by vic778 — COMMENTED** [review]
Hi @scientistsagoemarcus     , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Charlie Brown

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification

**Comment by scientistsagoemarcus** [comment]
Thank you senior

**Pull request merged**
