### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by scientistsagoemarcus**
This is a pull request from the master to the feature branch.

### CODE REVIEW

**Comment by scientistsagoemarcus** [comment]
Feature branch merged with the Master branch.

**Comment by vic778** [comment]
HI @scientistsagoemarcus you should use the previous PR as requested by the previous Code reviewer. however I'm gonna approve your PE because you did the change as requested  . Remember to add the description as i can see you did in the previous PR because the description explain what you have made in the branch.

**Review by vic778 — APPROVED** [review]
Hi @scientistsagoemarcus     , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Charlie Brown

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification

**Comment by scientistsagoemarcus** [comment]
Thank you boss and God Bless you.

**Pull request merged**
