### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by scientistsagoemarcus**

### CODE REVIEW

**Review by chrystalme — COMMENTED** [review]
## Hi @scientistsagoemarcus, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❗ 

You have submitted a project, that 
- does not have [linters](https://github.com/microverseinc/linters-config) setup for the project
-  your project does not have a professional [README.md](https://github.com/microverseinc/readme-template) file.


Also, kindly follow the project instruction and include a `.gitignore` file and `node_module/` and `test.md` files added to it. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @scientistsagoemarcus, 

Great work on making the changes requested by a previous reviewer 👏 .
You've done well implementing some of the requested changes like using properly the `.gitignore` file, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- Use of the `.gitignore` file very well
- Use of correct GitHub flow


 ## Required Changes ♻️

- [ ] I really appreciate your efforts in trying to set up linters correctly as has been requested by the previous reviewer, however, it has not yet been set correctly but you are so close 🏃. There is documentation about [setting up linters](https://github.com/microverseinc/linters-config/tree/master/html-css), you may have read it but you are not doing it the right way. See, you have added the whole `html-css` folder to your repo, while in order to setup GitHub linters action, we only need the `.github` folder  and the `.stylintrc.json` and `.hintrc` files as shown in the picture below
image
Please replace that folder with only the folder and two files shown above in your repository then check here on GitHub, they should run and display the result as you push 😺 

- [ ] About your README file, you really have done a great job while using the README template given 👏. However, as the previous reviewer mentioned, it lacks information, you can see section headings without supporting paragraph texts. You have to edit it and put the information specific to this project. You don't have to say much but at least give some information starting from the description, to getting started, how to use your project, languages used while building it, things like that. This helps everyone who visits your repo to get a clear understanding of it 😃. In addition, please remember to add your social media links in the Authors section plus your name. You are the author so people should know you 👍.

- [ ] You used the correct GitHub flow however your branch should be more descriptive about what you are going to do. Instead of calling it just `feature` you can call it `create-homepage` or `feature/homepage` or `add-html-css-files` just as an example. This will help others to know what you are currently working on 😃

- [ ] This goes together with your Pull request title. It is not really describing what you have done in this branch so that the review may get a clue on what to review. You should have called it `Build Hello Microverse page` or any descriptive title. Please correct that next time.

- [ ] Lastly, make sure that your Pull request has a descriptive body/description. In that place, you may list the things you built or added one by one or just add a text talking about what you have done. This also gives more information to the reviewer and therefore it is more easy to give you reviews👍.  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by scientistsagoemarcus** [comment]
Please do I need to create another pull request?

**Comment by BertrandConxy** [comment]
No you don't have to create another pull request. You should have pushed the requested changes on this branch which will appear under this pull request. Unfortunately, I can see that you have closed it and deleted it already.

**Comment by scientistsagoemarcus** [comment]
So please what do I do now? In that case,  please help me. Because I made
all the necessary changes and have pushed it.

**Comment by scientistsagoemarcus** [comment]
Immediately I pushed it shows a message that compare and pull request.

**Comment by scientistsagoemarcus** [comment]
Please what do I do for it to reflect on my dashboard?

**Pull request closed without merging**
